### PR TITLE
Add windows to azure pipline

### PR DESCRIPTION
**Pull request by bechurch**
## Summary
Adds a windows build to our azure pipeline

### CODE REVIEW

**Comment by expede** [comment]
[Add Win10 to build pipeline](https://trello.com/c/GBd0aTto/801-add-win10-to-build-pipeline)

**Comment by bechurch** [comment]
@expede @dholms This was originally time boxed for a week. I've paused work on this since Friday. Mostly because I've hit a road block. ANy ideas on how to get around it would be appreciated.

So far I've got this close to building locally and on azure however I cant seem to get passed this error:
> ghc.exe: unable to load package `streamly-0.6.1`
ghc.exe:  | C:\sr\snapshots\bfd66005\lib\x86_64-windows-ghc-8.6.5\streamly-0.6.1-8QWWqklcwJeEHbJUExjjJo\HSstreamly-0.6.1-8QWWqklcwJeEHbJUExjjJo.o: unknown symbol `clock_gettime'

[source](https://dev.azure.com/fission/fission-cli/_build/results?buildId=255&view=logs&jobId=f3265598-4cc6-5f81-9bda-0a19d8fde717&taskId=928f29a3-c608-5b89-1616-aa20c0863d92&lineStart=8151&lineEnd=8152&colStart=1&colEnd=1)

Digging a little deeper in appears to be an issue with GHC though this was from the `yesod` package not `streamly`
https://stackoverflow.com/questions/44489668/yesod-installation-unable-to-load-package-foundation-0-0-10

Anyone have some tips for getting around this?

**Comment by bechurch** [comment]
@dholms the streamly package was directly referenced in web-api however it appears like it was an unused dependency!

https://github.com/fission-suite/cli/pull/48

After removing it that compile error disappeared and all but the archive step now runs successfully!

**Comment by bechurch** [comment]
Wew everything is building, next is figuring out what is up with the cache 🤔

**Pull request merged**
